name: Контроль качества

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  sonar:
    uses: autumn-library/workflows/.github/workflows/sonar.yml@v1
    with:
      github_repository: autumn-library/autumn-killjoy-flavour
      test_engine: oneunit
      oscript_version: stable
      test_dir_paths: tests
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
